site_name: Pythonパッケージの作り方
docs_dir: sources
markdown_extensions:
  - admonition
theme:
  name: readthedocs
  language: 'jp'
extra:
  search:
    language: 'jp'

pages:
  - Home: index.md
  - Python実行環境: environment.md
  - プロジェクトの作成: project.md
  - PyPIへのアップロード: pypi.md
  - ローカルでのテスト: local-test.md
  - CIでのテスト: ci-test.md
  - Anacondaへのアップロード: anaconda.md
  - ビルドとデプロイの自動化: ci-deploy.md
